// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYCGtsbk0HtT01ZoVStd-pl_j6KcxJjTA',
    appId: '1:836592645166:web:114a327e2ec6c8ce025bbf',
    messagingSenderId: '836592645166',
    projectId: 'jamband-login-237af',
    authDomain: 'jamband-login-237af.firebaseapp.com',
    storageBucket: 'jamband-login-237af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSq7UvkJO38FpJmTYPIxC7gnyamz5XF8Q',
    appId: '1:836592645166:android:0c2ee3102d4640e2025bbf',
    messagingSenderId: '836592645166',
    projectId: 'jamband-login-237af',
    storageBucket: 'jamband-login-237af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlV63OkPa5zQVvu3l2YEXdBnMflOLxyEM',
    appId: '1:836592645166:ios:fbf01243d18eecd2025bbf',
    messagingSenderId: '836592645166',
    projectId: 'jamband-login-237af',
    storageBucket: 'jamband-login-237af.appspot.com',
    iosClientId:
        '836592645166-cbl2que49v15q7bkb425l5potttkhu4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.toonflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlV63OkPa5zQVvu3l2YEXdBnMflOLxyEM',
    appId: '1:836592645166:ios:fbf01243d18eecd2025bbf',
    messagingSenderId: '836592645166',
    projectId: 'jamband-login-237af',
    storageBucket: 'jamband-login-237af.appspot.com',
    iosClientId:
        '836592645166-cbl2que49v15q7bkb425l5potttkhu4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.toonflix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYCGtsbk0HtT01ZoVStd-pl_j6KcxJjTA',
    appId: '1:836592645166:web:659bd382f05ec1de025bbf',
    messagingSenderId: '836592645166',
    projectId: 'jamband-login-237af',
    authDomain: 'jamband-login-237af.firebaseapp.com',
    storageBucket: 'jamband-login-237af.appspot.com',
  );
}
